name: Docker Build and Push

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build -t simeonmarkoski/macedonian-stock-exchange-back-end-spring-app:latest .
          docker push simeonmarkoski/macedonian-stock-exchange-back-end-spring-app:latest
